### ISSUE TITLE
Status of GHCJS support

### ISSUE THREAD

**Issue by mgsloan** [fpco/store#43]
By using `stack test --compiler ghcjs-0.2.0.20160315_ghc-7.10.2`, I can actually run the test suite with ghcjs!!  It immediately fails due to using unimplemented C.  However, roundtripping `[Int]` does work.

```
store-0.1.0.1: test (suite: store-test)
             
Progress: 1/2
Data.Store.Streaming
  conduitEncode and conduitDecode
    Roundtrips ([Int]).
uncaught exception in Haskell thread: ReferenceError: h$realloc is not defined
ReferenceError: h$realloc is not defined
    at h$$gl7 (/home/mgsloan/fpco/store/.stack-work/dist/x86_64-linux/Cabal-1.22.4.0_ghcjs/build/store-test/store-test:347056:13)
    at h$runThreadSlice (/home/mgsloan/fpco/store/.stack-work/dist/x86_64-linux/Cabal-1.22.4.0_ghcjs/build/store-test/store-test:9788:11)
    at h$runThreadSliceCatch (/home/mgsloan/fpco/store/.stack-work/dist/x86_64-linux/Cabal-1.22.4.0_ghcjs/build/store-test/store-test:9742:12)
    at h$mainLoop (/home/mgsloan/fpco/store/.stack-work/dist/x86_64-linux/Cabal-1.22.4.0_ghcjs/build/store-test/store-test:9737:9)
    at /home/mgsloan/fpco/store/.stack-work/dist/x86_64-linux/Cabal-1.22.4.0_ghcjs/build/store-test/store-test:10300:13
    at /home/mgsloan/fpco/store/.stack-work/dist/x86_64-linux/Cabal-1.22.4.0_ghcjs/build/store-test/store-test:23046:17
    at FSReqWrap.strWrapper (fs.js:568:5)
thread blocked indefinitely in an ST             
store-0.1.0.1: test (suite: store-weigh)
             
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn a.jsexe ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1054:32)
    at child_process.js:1145:20
    at process._tickCallback (node.js:355:11)

Completed 2 action(s).
Test suite failure for package store-0.1.0.1
    store-test:  exited with: ExitFailure 1
    store-weigh:  exited with: ExitFailure 1
Logs printed to console
```

I tried commenting out the streaming tests, and got:

```
store-0.1.0.1: test (suite: store-test)
             
Progress: 1/2
Data.Store
  Store on all monomorphic instances
    Roundtrips (GHC.Word.Word8)
    Roundtrips (GHC.Word.Word64)
    Roundtrips (GHC.Word.Word32) FAILED [1]
    Roundtrips (GHC.Word.Word16)
    Roundtrips (GHC.Types.Word) FAILED [2]
    Roundtrips (Data.Void.Void)
uncaught exception in Haskell thread: unhandled primop: CopyByteArrayToAddrOp (0,5)
thread blocked indefinitely in an ST             
store-0.1.0.1: test (suite: store-weigh)
             
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn a.jsexe ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1054:32)
    at child_process.js:1145:20
    at process._tickCallback (node.js:355:11)

Completed 2 action(s).
Test suite failure for package store-0.1.0.1
    store-test:  exited with: ExitFailure 1
    store-weigh:  exited with: ExitFailure 1
Logs printed to console
```

There, it's failing on the serialization of `Data.Vector.Unboxed.Base.Vector GHC.Word.Word64`.

So there are a couple missing things: `CopyByteArrayToAddrOp` and `realloc`.  Not sure if it's even possible to implement these.

We have a few choices for what to do about this:

1) Leave it, GHCJS users will need to be sure to test!
2) CPP to remove the things not supported by GHCJS.  Seems fiddly
3) Get the requisite FFI / primops added to GHCJS

**Comment by mgsloan** [comment]
Those decode errors are curious too.  I turned on verbose debugging to get some insight:

```
Data.Store
  Store on all monomorphic instances
("encoded","\255")
("decoded",Right 255)
("encoded","\NUL")
("decoded",Right 0)
("encoded","\SOH")
("decoded",Right 1)
    Roundtrips (GHC.Word.Word8)
("encoded","\255\255\255\255\255\255\255\255")
("decoded",Right 18446744073709551615)
("encoded","\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL")
("decoded",Right 0)
("encoded","\NUL\NUL\NUL\NUL\SOH\NUL\NUL\NUL")
("decoded",Right 1)
    Roundtrips (GHC.Word.Word64)
("encoded","\255\255\255\255")
("decoded",Right 4294967295)
    Roundtrips (GHC.Word.Word32) FAILED [1]
("encoded","\255\255")
("decoded",Right 65535)
("encoded","\NUL\NUL")
("decoded",Right 0)
("encoded","\SOH\NUL")
("decoded",Right 1)
    Roundtrips (GHC.Word.Word16)
("encoded","\255\255\255\255")
("decoded",Right 4294967295)
    Roundtrips (GHC.Types.Word) FAILED [2]
    Roundtrips (Data.Void.Void)
```

No such insight - those values look fine. Hrrrm
